# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\code\python\hrm-pytorch\controller\recovery_learning.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtMultimedia import *
from PyQt5.QtMultimediaWidgets import QVideoWidget


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(876, 731)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(501, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(45)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(500, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_video = QtWidgets.QWidget(self.widget_2)
        self.widget_video.setMinimumSize(QtCore.QSize(640, 480))
        self.widget_video.setObjectName("widget_video")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_video)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_3.addWidget(self.widget_video)
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_1 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_1.setMinimumSize(QtCore.QSize(95, 35))
        self.pushButton_1.setMaximumSize(QtCore.QSize(95, 35))
        self.pushButton_1.setObjectName("pushButton_1")
        self.verticalLayout.addWidget(self.pushButton_1)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_2.setMinimumSize(QtCore.QSize(95, 35))
        self.pushButton_2.setMaximumSize(QtCore.QSize(95, 35))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_3.setMinimumSize(QtCore.QSize(95, 35))
        self.pushButton_3.setMaximumSize(QtCore.QSize(95, 35))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_4.setMinimumSize(QtCore.QSize(95, 35))
        self.pushButton_4.setMaximumSize(QtCore.QSize(95, 35))
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.horizontalLayout_3.addWidget(self.widget_4)
        self.verticalLayout_2.addWidget(self.widget_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 876, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.widget_mediaw = QVideoWidget(self.widget_video)
        self.widget_mediaw.setMinimumSize(QtCore.QSize(640, 480))
        self.widget_mediaw.setMaximumSize(QtCore.QSize(640, 480))
        self.widget_mediaw.setObjectName("widget_mediaw")
        self.playlist = QMediaPlaylist(self.widget_video)
        self.playlist.addMedia(QMediaContent(QtCore.QUrl.fromLocalFile('./resource/sampleVideo/dynamic/allHands.avi')))
        self.playlist.setPlaybackMode(QMediaPlaylist.CurrentItemInLoop)
        self.player1 = QMediaPlayer(self.widget_video)
        self.player1.setObjectName("player1")
        self.player1.setVideoOutput(self.widget_mediaw)
        self.player1.setPlaylist(self.playlist)
        self.player1.play()

        self.retranslateUi(MainWindow)
        self.pushButton_1.clicked.connect(MainWindow.action_1)
        self.pushButton_2.clicked.connect(MainWindow.action_2)
        self.pushButton_3.clicked.connect(MainWindow.action_3)
        self.pushButton_4.clicked.connect(MainWindow.action_4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "康复学习"))
        self.pushButton_1.setText(_translate("MainWindow", "康复训练"))
        self.pushButton_2.setText(_translate("MainWindow", "自我训练"))
        self.pushButton_3.setText(_translate("MainWindow", "手势锻炼"))
        self.pushButton_4.setText(_translate("MainWindow", "功能锻炼"))
